### ISSUE TITLE
Issue with Verifying MaxPool Layers in auto_LiRPA

### ISSUE THREAD

**Issue by r11942152** [Verified-Intelligence/auto_LiRPA#56]
Dear auto_LiRPA Team,

Thanks for your work! 
It has been a valuable tool for us.

We are writing to report an issue we've encountered when trying to use the **simple_verification.py** script with a model containing **nn.MaxPool2d()** layers. We will provide more details about the problem we are facing and kindly request your guidance or assistance in resolving it.

The Problem:
The  **simple_verification.py** script worked perfectly with your provided model and checkpoint.
And, we have successfully used the **simple_verification.py** script to verify models without **nn.MaxPool2d()** layers by running the following command:
```
python simple_verification.py
```
when we created the ``BoundedModule`` with:
```
lirpa_model = BoundedModule(
    model, torch.empty_like(image), device=image.device,
    bound_opts={
        'sparse_features_alpha': False,
        'sparse_spec_alpha': False,
    })
```
However, when we attempted to use the same script with a model that includes MaxPool layers, as shown in the code snippet below:
```
def conv_MP():
    model = nn.Sequential(
        nn.Conv2d(1, 16, 4, stride=2, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
        nn.Conv2d(16, 32, 4, stride=2, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
        Flatten(),
        nn.Linear(32, 24),
        nn.ReLU(),
        nn.Linear(24, 10)
    )
    return model
```

we encountered a TypeError:
```
Bounding method: CROWN-Optimized (alpha-CROWN)
[1, 10, 3, 3, 16, 8, 8] [32, 10, 3, 3, 16, 8, 8] [1, 10, 3, 3, 16, 8, 8] [32, 10, 3, 3, 16, 8, 8]
[32, 10, 3, 3] []
[1, 10, 3, 3, 16, 8, 8] [32, 10, 3, 3, 16, 8, 8] [1, 10, 3, 3, 16, 8, 8] [32, 10, 3, 3, 16, 8, 8]
[] [32, 10, 3, 3]
[1, 10, 32, 3, 3] [24, 10, 32, 3, 3] [1, 10, 32, 3, 3] [24, 10, 32, 3, 3]
[24, 10] []
[1, 10, 32, 3, 3] [24, 10, 32, 3, 3] [1, 10, 32, 3, 3] [24, 10, 32, 3, 3]
[] [24, 10]
[1, 10, 16, 14, 14] [24, 10, 16, 14, 14] [1, 10, 16, 14, 14] [24, 10, 16, 14, 14]
[24, 10] []
[1, 10, 16, 14, 14] [24, 10, 16, 14, 14] [1, 10, 16, 14, 14] [24, 10, 16, 14, 14]
[] [24, 10]
[1, 10, 24] [10, 10, 24] [1, 10, 24] [10, 10, 24]
[10, 10] []
[1, 10, 24] [10, 10, 24] [1, 10, 24] [10, 10, 24]
[] [10, 10]
[1, 10, 32, 3, 3] [10, 10, 32, 3, 3] [1, 10, 32, 3, 3] [10, 10, 32, 3, 3]
[10, 10] []
[1, 10, 32, 3, 3] [10, 10, 32, 3, 3] [1, 10, 32, 3, 3] [10, 10, 32, 3, 3]
[] [10, 10]
[1, 10, 16, 14, 14] [10, 10, 16, 14, 14] [1, 10, 16, 14, 14] [10, 10, 16, 14, 14]
[10, 10] []
[1, 10, 16, 14, 14] [10, 10, 16, 14, 14] [1, 10, 16, 14, 14] [10, 10, 16, 14, 14]
[] [10, 10]
Traceback (most recent call last):
  File "simple_verification2.py", line 152, in <module>
    lb, ub = lirpa_model.compute_bounds(x=(image,), method=method.split()[0])
  File "/home/user/anaconda3/envs/LiRPA/lib/python3.8/site-packages/auto_LiRPA-0.3.1-py3.8.egg/auto_LiRPA/bound_general.py", line 1188, in compute_bounds
    ret1 = self.get_optimized_bounds(
  File "/home/user/anaconda3/envs/LiRPA/lib/python3.8/site-packages/auto_LiRPA-0.3.1-py3.8.egg/auto_LiRPA/optimized_bounds.py", line 457, in get_optimized_bounds
    self.init_slope(x, share_slopes=opts['use_shared_alpha'],
  File "/home/user/anaconda3/envs/LiRPA/lib/python3.8/site-packages/auto_LiRPA-0.3.1-py3.8.egg/auto_LiRPA/optimized_bounds.py", line 1055, in init_slope
    node.init_opt_parameters(start_nodes)
  File "/home/user/anaconda3/envs/LiRPA/lib/python3.8/site-packages/auto_LiRPA-0.3.1-py3.8.egg/auto_LiRPA/operators/pooling.py", line 50, in init_opt_parameters
    self.alpha[ns] = torch.empty(
TypeError: empty(): argument 'size' must be tuple of ints, but found element of type tuple at pos 2
```
We noticed that the models provided in the **examples/vision/models directory** do not contain MaxPool layers. If the library does not currently support **nn.MaxPool2d()**  layers, we would appreciate guidance on how to adapt the verification process or any potential workarounds.

Your support and guidance in resolving this issue would be greatly appreciated.
Additionally, you can download our parameters from
```
wget -O Conv_MP.pth https://www.dropbox.com/scl/fi/qpz1615ssfpegwam2dmka/Conv-MP.pth?rlkey=7081ipy9b58p0ug84xswvs528&dl=1
```
System configuration:

OS: Ubuntu 18.04.6 LTS
Python version: Python 3.7.13
Pytorch Version: PyTorch 1.11.0
Hardware: NVIDIA GeForce GTX 1080 Ti
Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: No, we used the main branch in September 2023 since some packages in the latest environment cannot be installed correctly.

**Comment by shizhouxing** [comment]
Please additionally set `'conv_mode': 'matrix'` in `bound_opts`.

**Comment by huanzhang12** [comment]
Using `'conv_mode': 'matrix'` will significantly reduce performance and is not recommended. @r11942152 although you can try it and see if that works, the verifier may run really slowly or out of memory, especially when network is slightly larger.

@shizhouxing I believe we had working maxpooling before, and it has been supported for a long time. The example provided by @r11942152 is simple and we should fix it. Recently, we might have changed the optimization variable interface for other optimizable functions, and maxpool was not updated accordingly. Can you take a look and fix it? You can ask @C-lister to help if needed. Thanks.

**Comment by r11942152** [comment]
@shizhouxing I've added ``'conv_mode': 'matrix'`` to the ``bound_opts``, but the same bug persists. It's possible that the bug is related to ``nn.MaxPool2d(2),``,  so changing ``'conv_mode': 'matrix'`` may not resolve the issue.

**Comment by shizhouxing** [comment]
`conv_mode` is also related to the implementation in maxpool. It's a temporary workaround. 

@r11942152  It looks like you may not be using the latest version of auto_LiRPA, since I see that the code line numbers in your tracekback don't match the latest code. Could you please try the latest release?
